### ISSUE TITLE
Sequencing decoders

### ISSUE THREAD

**Issue by sshquack** [Gozala/decoder.flow#1]
Hi @Gozala,

I've been wanting to use elm-like decoder in flow, and thank you so much for this wonderful library!

In the current version of this library, is there a way to sequentially combine decoders? The decoded `Result` type has a `map` which happens after the execution of a `decode` or `parse`. But I'm looking for something that does it during definition. The type signature mimics elm's definition:

```
Decoder.andThen( 
  fn: (T) => Decoder.Decoder<U>, 
  de: Decoder.Decoder<T> 
): Decoder.Decoder<U>
```

**Comment by Gozala** [comment]
Hi @sshquack thanks for you kind words. Unfortunately this library **intentionally** diverged from Elm in that regard and omits `map` and `andThen` combinators. That is because my primary use case for it is in [DOMinion](https://github.com/gozala/dominion) library which provides a Virtual DOM API which apps could run in a web-worker and then reflect it on the main thread. Decoders there are used instead of event handlers and provide a way to extract relevant  details at the event site (main thread), this adds a constraint (not present in Elm) that decoders need to be transferred from worker thread to the main thread, which works fine with this implementation as decoders are just JSON objects. Combinators like `map` and `andThen` would require to store passed functions on the decoder objects and there for they will no longer be transferable them across threads (functions and their scope chains make it impossible in JS), there for I have decided to not have those combinators. I do intend to provide some mechanism for logic branching, something like `function when <a>  (condition:Decoder<boolean>, then:Decoder<a>, else:Decoder<a>):Decoder<a>`.

Now that being said, it should be fairly easy to wrap this library and provide those additional combinators & I would be happy to help with that effort.

**Comment by Gozala** [comment]
If you have specific use case in mind please let me know and maybe there is a way it can be handled without compromising cross thread transfer-ability of decoders, in which case I'll likely will be willing (unless use case is exotic) to add support for it.

**Comment by Gozala** [comment]
@sshquack oh one more thing, I do want to allow things like `map` and `andThen` but at the different layer something like:

```js
const onClick = on('click', Decoder.record({ 
  type: Decoder.string,
  button: Decoder.Integer,
  ctrlKey: Decoder.Boolean
}))

DOMinion.div([
  onClick.map(Clicked)
], [ ... ])
```

**Comment by Gozala** [comment]
I actually just realized that to support example from Elm docs on `andThen`:

```elm
info : Decoder Info
info =
  field "version" int
    |> andThen infoHelp

infoHelp : Int -> Decoder Info
infoHelp version =
  case version of
    4 ->
      infoDecoder4

    3 ->
      infoDecoder3

    _ ->
      fail <|
        "Trying to decode info, but version "
        ++ toString version ++ " is not supported."

-- infoDecoder4 : Decoder Info
-- infoDecoder3 : Decoder Info
```
I could expose something like following:

```js
Decoder.when(
  Decoder.field("version", Decoder.Integer),
  Decoder.ok(4), infoDecoder4,
  Decoder.ok(3), infoDecoder3,
  Decoder.error("Trying to decode info, but version isn't supported")
```
Which unlike Elm example won't be able to include `version` encountered in the error message, but would not require transfer-ability compromise.

**Comment by sshquack** [comment]
Really appreciate the prompt and detailed response on this! After learning a bit more about DOMinion, I agree that serializing complex functions would make transferring decoders really complicated. The Elm `andThen` example nicely fits into your proposed `when` for a two-level branching.

The use case I had in mind when I opened this issue was extensibility to return custom types. For example: `Decoder.field('uuid', Decoder.string).andThen(val => Uuid.decoder(val))` (assume that it internally uses an the empty decoder `ok` and in-turn calls `andThen`) I can see this feature being really valuable to build rich libraries like type-safe json schema decoder, various types of validation decoders (email, url etc), and even to build http codecs library. There is no immediate need for `andThen` or `map` because `Result.map` can be used as a work around and `Decoder.form` does a fantastic job of nested composition.

But perhaps there might be a way to create, say a `strict` by default mode in the library, where only serializable built-in decoders are allowed, and when `strict` is off it allows custom extensions with andThen or map. I'm poking around this code to understand how to build on top of this. I'll create a separate issue with a proposal as I close this one for now.

Overall the combination of `decoder.flow`, `router.flow`, and `result.flow` will help build a lot of type-safe backend components which is quiet exciting. So thank you again for all your well-documented, and well-tested .flow libraries! 🙇

**Comment by Gozala** [comment]
> Really appreciate the prompt and detailed response on this! After learning a bit more about DOMinion, I agree that serializing complex functions would make transferring decoders really complicated. The Elm andThen example nicely fits into your proposed when for a two-level branching.

Thanks for the feedback, I've added the issue https://github.com/Gozala/decoder.flow/issues/2 and will try to get into next major version.

> The use case I had in mind when I opened this issue was extensibility to return custom types. For example: Decoder.field('uuid', Decoder.string).andThen(val => Uuid.decoder(val)) (assume that it internally uses an the empty decoder ok and in-turn calls andThen) I can see this feature being really valuable to build rich libraries like type-safe json schema decoder, various types of validation decoders (email, url etc), and even to build http codecs library. There is no immediate need for andThen or map because Result.map can be used as a work around and Decoder.form does a fantastic job of nested composition.

I do not understand that example, specifically what does `Uuid.decoder` requires `val` or why `Decoder.field('uuid', UUIDdecoder)` can't be used instead ? Would you mind writing up complete example so I can try to address it with some combinator ? I think chaining decoding results can be added as described in #2  but then I'm not sure what would be a value of that since type information is going to be lost as decoders expect anything not a specific type. Although that is something that could be reconsidered.

> But perhaps there might be a way to create, say a strict by default mode in the library, where only serializable built-in decoders are allowed, and when strict is off it allows custom extensions with andThen or map. 

I really don't think adding modes here would be better option than just a making a new library that includes this and provides additional things like `andThen`. Modes would more fragile, require more maintenance and would be hard to play well with type system.

> I'm poking around this code to understand how to build on top of this. I'll create a separate issue with a proposal as I close this one for now.  

I think simplest way to go about it would be to extend this library to support generic use case, by which I mean extend the [following type union](https://github.com/Gozala/decoder.flow/blob/master/src/Decoder/Decoder.js#L25-L43) to add a `| ExternalDecoder<a>` that would have following interface

```js
interface ExternalDecoder<a> {
  type: "External",
 decode(mixed):Decode<a>
}
```

Then in third party library you would be able to do just following:

```js
class AndThen <a, b> implements ExternalDecoder<b> {
  type = "External"
  decoder:Decoder<a>
  next: a => Decoder<b>
  constructor(decoder:Decoder<a>, next: a => Decoder<b>) {
    this.decoder = decoder
    this.next = next
  }
  decode(input:mixed):Decode<b> {
    const value = Variant.decode(this.decoder, input)
    if (value instanceof Decoder.Error) {
      return value
    } else {
      return Variant.decode(this.next(value), input)
    }
  }
}

export const andThen = <a, b> (next:a => Decoder<b>, decoder:Decoder<a>):Decoder<b> =>
  new AndThen(decoder, next)

export { .... } from "decoder.flow"
```

**Comment by sshquack** [comment]
Sorry for not providing a concrete example earlier. The idea of creating an `ExternalDecoder` interface looks much cleaner! Here is my full Elm example that I was trying to convert to `decoder.flow`:

```
module Main exposing (main)

import Date exposing (Date)
import Html exposing (Html, text)
import Json.Decode exposing (Decoder, andThen, decodeString, fail, string, succeed)
import Uuid exposing (Uuid, fromString)


main : Html msg
main =
    text (toString (decodeString uuidDecoder "\"63B9AAA2-6AAF-473E-B37E-22EB66E66B76\""))


uuidDecoder : Decoder Uuid
uuidDecoder =
    let
        convertAndLift : String -> Decoder Uuid
        convertAndLift str =
            case fromString str of
                Just uuid ->
                    succeed uuid

                Nothing ->
                    fail ("Invalid uuid: " ++ str)
    in
    string |> andThen convertAndLift
```

Please note that I intentionally used `Uuid.fromString` which returns a `Maybe Uuid` instead of the more direct `Uuid.decoder` because it roughly maps to the js-land library facilities. So the idea is to leverage an existing js library but wrap it in a custom decoder. The above sample code can also be run live on [Ellie here](https://ellie-app.com/7DwT4K73ca1/0). Hope this helps!

**Comment by Gozala** [comment]
> Sorry for not providing a concrete example earlier. The idea of creating an ExternalDecoder interface looks much cleaner!

Cool! In fact `ExternalDecoder` was the actual `Decoder` interface originally I just changed it to make transfer across threads more straight forward. I was actually considering to add something like `ExternalDecoder` already so given the interest I'll just get it into next release. (Pull requests are also welcome and ;)

> Please note that I intentionally used Uuid.fromString which returns a Maybe Uuid instead of the more direct Uuid.decoder because it roughly maps to the js-land library facilities. So the idea is to leverage an existing js library but wrap it in a custom decoder. The above sample code can also be run live on Ellie here. Hope this helps!

I think your example boils down to authoring a "custom decoder" which does not really needs all of what `andThen` provides, as decoder returned by you `convertAndLift` does not really cares about original input, it's more like map over the result. This is actually could fit really well my design concerns in regards to `DOMinion`. I could provide something like:

```js
function chain <a, b> (Decoder<a>, a => Decode<b>):Decoder<b>
// P.S.: type Decode<b> = DecoderError | b
```

While this does imply that decoder contains a function it's actually not a problem here as it's always processes data extracted by core decoders so in DOMinion I could transfer root decoder, pass extracted data to the web-worker and run rest of the chain there. Note that with `andThen` it was not possible because returned decoder needs original input not just data that decoder extracted.

**Comment by Gozala** [comment]
With that I prefer to add `LiftDecoder<*, a>` to the mentioned type union over the earlier mentioned `ExternalDecoder<a>`:

```js
interface LiftDecoder<a, b> {
  root:Decoder<a>
  lift:a => Decode<b>
}
```

**Comment by sshquack** [comment]
The chain function type signature makes sense to me, and it also resembles the `Result.chain` from reading the docs - Thanks! Hoping the `Decoder.chain` will greatly simplify the necessity to run the decode phase for things like enums as well.
```js
type FooType1 = string;
type FooType2 = 'bar' | 'baz';

const fooResult1: Decoder.Result<FooType1> = Decoder.decode(Decoder.String, 'bar')
const fooResult2Fun = (s: string): Result.Result<*, FooType2> => {
  if (s === 'bar' || s === 'baz') {
    return Result.ok((s: FooType2));
  } else {
    return Result.error(new Decoder.Error('some error'));
  }
};
fooResult1.chain(fooResult2Fun);
```
